Algoritmo "Meu Primeiro Algoritmo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Cleison Melo
// Descrição   : Primeiro algoritmo para aprender a mexer no visualg
// Autor(a)    : Debora Fantini Fernandes
// Data atual  : 01/09/2020
Var
// Seção de Declarações das variáveis 
   idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   idade <- 19
   escreva ("Eu tenho", idade, " anos de idade")

Fimalgoritmo